# Generated by Django 4.2.7 on 2024-09-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climber',
            name='price',
        ),
        migrations.AddField(
            model_name='climber',
            name='peak',
            field=models.CharField(blank=True, null=True),
        ),
    ]
